# Prometheus configuration for Event-Driven PoC monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'event-driven-poc'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # API Service
  - job_name: 'api-service'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Mailer Service
  - job_name: 'mailer-service'
    static_configs:
      - targets: ['mailer:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true

  # Workflow Agent
  - job_name: 'workflow-agent'
    static_configs:
      - targets: ['workflow-agent:8002']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # Frontend (if metrics enabled)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 5s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# Storage configuration

